### ISSUE TITLE
Connecting skills to DH projects

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/command-line#14]
Is there an explicit place where we can connect the lesson and why working from the command line (at least knowing how to do it even if you don't want to do it all the time) is important for a humanities scholar who's interested in digital projects. 

I can imagine connecting this to Stephen Ramsay's blog post "Life on the Command Line," which I'm trying to find a copy of since his site seems to be down at the moment. 

For example, it's hard to install your own version of Omeka or even WordPress if you don't know how to  interact with the command line. You'll need to learn how to use the commands if you'd like to ssh into a host... and that might be important if you want to work with files that are on another computer.

**Comment by jojokarlin** [comment]
Lisa -- I tend to include a lot of this information as I go in my teaching. I don't want to overburden the text of the tutorial itself. I added more in the "What next" section of summary.md. I would like to keep as much as possible of this additional tie-in out of the flow of the lesson itself. I find that it is already overwhelming to see the commands. These questions will surely come up as we go, but it's better to let some of them come up as questions rather than trying to anticipate when people will feel ready to receive that information. Hope that comes through.
