### ISSUE TITLE
Prerequisites, Projects, and Ethical Concerns?

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#55]
Any thoughts on how to fill out these sections for the Command Line workshop?

**Comment by lmrhody** [comment]
- [x] You might read through the lesson and then look for the most recent installation guide that we've used. That would help cover, for example, the fact that they'll need to know what operating system they're using and then which version of BASH they will need. (if it's a windows machine, this matters). They also need a text editor of some sort (we encourage VS Code). 

- [x] In the Zotero library, there are lots of readings that could be useful. Some from Code Academy on how the computer works, for example. Since this is the first workshop that we offer, we want to build out resources that help set the student up with a vocabulary they can build from. 

- [x] Kelsey's version of this workshop has a lot of information about the ethical issues to consider. For example, there's the issue of "command and control center" which means that the operating system builds on a military logic. 

- [x] For projects, what is important is to think about how knowing the command line and how to use it helps create a project. For someone working on Omeka, knowing about the command line would help you, for example, set up an installation of Omeka-S and to add plugins to an installation.

**Comment by gofilipa** [comment]
I have a few suggestions for prerequisites, pulling from the Zotero library & from my own research:

- **A brief history of the command line** by Free Code Camp, probably the best and most readable overview about why the command line and what it can do: https://www.freecodecamp.org/news/the-command-line-1fdbc692b3bf/
- **The Bash Manual** by Free Software Foundation, which is a comprehensive documentation on Bash: https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html
- a forum thread about **the differences (and history) of terminal vs. bash** (pretty interesting background): https://unix.stackexchange.com/questions/180943/terminal-vs-bash
- **basic Unix commands** (a useful cheat sheet for the command line): http://mally.stanford.edu/~sr/computing/basic-unix.html

Here's something that might be useful in "Theory and Practice" page---a tutorial on how to use the command line for **pandoc**, an awesome program which allows users to switch file types (from markdown to pdf to docx, for example). This would be intermediate level stuff. https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown

Hope this helps!

**Comment by smorello87** [comment]
Thank you so much, both!!!
