### ISSUE TITLE
Format of Assessment.md

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#57]
I copy/pasted questions from previous DRI/DHRI exit slips, but not sure if that's the kind of formatting you wanted us to use!

**Comment by kallewesterling** [comment]
It looks good, @smorello87! I have not been working as hard this sprint on the assessment because I think we need to revisit it after the lessons-focused sprint, so I will tag this issue in my "collector issue" for the website. Feel free to close this issue (#57) if it bothers you to have it open. Otherwise, just leave it open :)
