### ISSUE TITLE
Should I keep Jojo's name in the examples?

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#60]
Some of the [lessons](https://github.com/DHRI-Curriculum/command-line/blob/v2.0-smorello-edits/lessons.md) were written by Jojo and use her username as an example. I think it makes sense to keep that as is, unless someone thinks it would be confusing for the institute participants if I come up as workshop leader and Jojo's name appears throughout the lessons?

**Comment by kallewesterling** [comment]
Ah I see now that maybe this issue was less related to Jojo's name than I thought the issue was here. Now that I'm looking over the lessons, how do you feel about putting `your-username` or something like that, in Jojo's place? Unless that gets too impersonal, I think that's the way to go — making it as evergreen as possible.

**Comment by smorello87** [comment]
Got it! Thank you!!
