### ISSUE TITLE
Reference to next workshops

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/command-line#62]
Hi all! 
Unsure what to do with [this section](https://github.com/DHRI-Curriculum/command-line/blob/v2.0-smorello-edits/lessons.md#before-we-finish), as it mentions the workshops that have been historically taught after the command-line one. If you anticipate the DHRI is going to follow the same structure as in the past, and will be building up on the command-line as well, I can leave as is, otherwise, we should return to it once we have a better understanding of the larger picture?

**Comment by kallewesterling** [comment]
Remove things like that. We're moving the curriculum to be more evergreen than it has been before, and I think it's important to keep learners' "freedom in movement" across workshops. But this raises an idea for me that we keep something like "suggested following workshops" in the `meta.md` file that we've been thinking of for the workshops:

https://github.com/DHRI-Curriculum/project-lab/issues/17

@lmrhody that sounds like a good idea, no?

**Comment by kallewesterling** [comment]
I'll remind everyone about this in our next sprint kick-off meeting but a heads-up, since you opened the issue: I think we need to get rid of any temporal references (e.g. "as you move forward through the week") and references to other workshops in the lessons text. It will, if anything, live separately in the website's ecosystem (like a `tracks` feature or something like that). Separating these things out will help us in the DHRI grant, since different institutes will want to use different workshops and create their own paths through our curricular content.

**Comment by smorello87** [comment]
Thank you, K!
